web/router.ex
defmodule UltraSonicPi.Router do
  use UltraSonicPi.Web, :router

  use ExAdmin.Router
  # your app's routes
  scope "/admin", ExAdmin do
    pipe_through :browser
    admin_routes()
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_user_token
  end

  pipeline :authenticated_routes do
    plug :require_authentication
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :socket do
  end

  scope "/", UltraSonicPi do
    pipe_through :browser

    get "/", PageController, :index

    post "/sign_in", AuthController, :authenticate
    get "/sign_in", AuthController, :sign_in
    get "/logout", AuthController, :logout, as: :logout
  end

  scope "/", UltraSonicPi do
    pipe_through [:browser, :authenticated_routes]

    resources "/songs", SongController do
      resources "/messages", MessageController, only: [:index, :new, :create]
    end
  end

  defp put_user_token(conn, _) do
    token = get_session(conn, "user_token")
    username = UltraSonicPi.User.verify_token(conn, token)

    conn
    |> assign(:user_token, token)
    |> assign(:username, username)
  end

  defp require_authentication(conn, _) do
    token = get_session(conn, "user_token")
    username = UltraSonicPi.User.verify_token(conn, token)

    if username do
      conn
    else
      conn
      |> put_flash(:info, "You must sign in to view this page")
      |> redirect(to: "/sign_in")
      |> halt()
    end
  end
end

lib/ultra_sonic_pi/endpoint.ex
defmodule UltraSonicPi.Endpoint do
  use Phoenix.Endpoint, otp_app: :ultra_sonic_pi

  socket "/socket", UltraSonicPi.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :ultra_sonic_pi, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_ultra_sonic_pi_key",
    signing_salt: "8p51v97+"

  # TODO: set encryption_salt ^^^

  plug UltraSonicPi.Router
end

lib/ultra_sonic_pi/repo.ex
defmodule UltraSonicPi.Repo do
  use Ecto.Repo, otp_app: :ultra_sonic_pi
  use Scrivener, page_size: 10
end

web/models/message.ex
defmodule UltraSonicPi.Message do
  use UltraSonicPi.Web, :model

  schema "messages" do
    field :body, :string
    belongs_to :song, UltraSonicPi.Song

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:body])
    |> validate_required([:body])
  end
end

web/models/song.ex
defmodule UltraSonicPi.Song do
  use UltraSonicPi.Web, :model

  schema "songs" do
    field :body, :string
    field :title, :string
    has_many :messages, UltraSonicPi.Message

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:body, :title])
    |> validate_required([:body, :title])
    |> validate_length(:title, min: 3)
  end
end

web/models/user.ex
defmodule UltraSonicPi.User do
  use UltraSonicPi.Web, :model

  @salt Application.get_env(:ultra_sonic_pi, :auth_salt)

  @doc """
  Veryfies an auth token and returns a username
  or nil if unable to decrypt the auth token / expired
  """
  def verify_token(conn, token) do
    case Phoenix.Token.verify(conn, @salt, token, max_age: 1209600) do
      {:ok, username} ->
        username
      {:error, _reason} ->
        nil
    end
  end
end

web/controllers/auth_controller.ex
defmodule UltraSonicPi.AuthController do
  use UltraSonicPi.Web, :controller

  @salt Application.get_env(:ultra_sonic_pi, :auth_salt)

  def authenticate(conn, %{"user" => %{"username" => username}})
  when not username in ["", nil] do
    token = Phoenix.Token.sign(conn, @salt, username)

    conn
    |> put_session(:user_token, token)
    |> put_flash(:info, "Successfully signed in")
    |> redirect(to: song_path(conn, :index))
  end

  def authenticate(conn, _) do
    conn
    |> put_flash(:error, "Please provide a username")
    |> render("sign_in.html")
  end

  def sign_in(conn, _) do
    conn |> render("sign_in.html")
  end

  def logout(conn, _) do
    conn
    |> put_session(:user_token, nil)
    |> assign(:username, nil)
    |> assign(:user_token, nil)
    |> put_flash(:info, "Successfully signed out")
    |> render("sign_in.html")
  end
end

web/controllers/message_controller.ex
defmodule UltraSonicPi.MessageController do
  use UltraSonicPi.Web, :controller

  alias UltraSonicPi.Message
  alias UltraSonicPi.Song

  plug :find_song

  def index(conn, _params) do
    song = conn.assigns.song
    messages = Repo.all(from m in assoc(song, :messages))
    render(conn, "index.html", messages: messages)
  end

  def new(conn, _params) do
    changeset = Message.changeset(%Message{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"message" => message_params}) do
    song = conn.assigns.song
    changeset =
      song
      |> Ecto.Model.build(:messages)
      |> Message.changeset(message_params)

    case Repo.insert(changeset) do
      {:ok, _message} ->
        conn
        |> put_flash(:info, "Message created successfully.")
        |> redirect(to: song_message_path(conn, :index, song))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  defp find_song(conn, _) do
    assign(conn, :song, Repo.get!(Song, conn.params["song_id"]))
  end
end

web/controllers/page_controller.ex
defmodule UltraSonicPi.PageController do
  use UltraSonicPi.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/song_controller.ex
defmodule UltraSonicPi.SongController do
  use UltraSonicPi.Web, :controller

  alias UltraSonicPi.Song

  def index(conn, _params) do
    songs = Repo.all(Song)
    render conn, "index.html", songs: songs
  end

  def show(conn, %{"id" => id} = _params) do
    song = Repo.get!(Song, id)
    render conn, "show.html", song: song
  end
end

web/views/auth_view.ex
defmodule UltraSonicPi.AuthView do
  use UltraSonicPi.Web, :view

end

web/views/error_view.ex
defmodule UltraSonicPi.ErrorView do
  use UltraSonicPi.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule UltraSonicPi.LayoutView do
  use UltraSonicPi.Web, :view
end

web/views/message_view.ex
defmodule UltraSonicPi.MessageView do
  use UltraSonicPi.Web, :view
end

web/views/page_view.ex
defmodule UltraSonicPi.PageView do
  use UltraSonicPi.Web, :view
end

web/views/song_view.ex
defmodule UltraSonicPi.SongView do
  use UltraSonicPi.Web, :view

end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= tag :meta, name: "user_token", content: @user_token %>

    <title>Hello UltraSonicPi!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://codemirror.net/lib/codemirror.css">
    <link rel="stylesheet" href="https://codemirror.net/theme/dracula.css">
    <script src="https://codemirror.net/lib/codemirror.js"></script>
    <script src="https://codemirror.net/keymap/vim.js"></script>
    <script src="https://codemirror.net/mode/ruby/ruby.js"></script>
    <script src="https://codemirror.net/mode/xml/xml.js"></script>
    <style>
    </style>
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if @user_token do %>
              <li><%= @username %></li>
              <li><%= link("logout", to: logout_path(@conn, :logout)) %></li>
            <%= else %>
              <li><%= link("sign in", to: auth_path(@conn, :sign_in)) %></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/message/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/message/index.html.eex
<h2>Listing messages for <%= @song.title %></h2>

<table class="table">
  <thead>
    <tr>
      <th>Song</th>
      <th>Body</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for message <- @messages do %>
    <tr>
      <td><%= message.song_id %></td>
      <td><%= message.body %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New message", to: song_message_path(@conn, :new, @song) %>

web/templates/message/new.html.eex
<h2>New message</h2>

<%= render "form.html", changeset: @changeset,
                        action: song_message_path(@conn, :create, @song) %>

<%= link "Back", to: song_message_path(@conn, :index, @song) %>

web/templates/song/index.html.eex
<h2>Listing Songs</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for song <- @songs do %>
      <tr>
        <td><%= song.title %></td>
        <td class="text-right">
          <%= link "Edit", to: song_path(@conn, :show, song) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

web/templates/song/show.html.eex
<h1><%= @song.title %></h1>

<div id="app-container">

</div>

<form>
  <textarea id="codeContainer" data-id="<%= @song.id %>"><%= @song.body %></textarea>
</form>

<ul id="message-log" />
<button id="playButton">Play</button>